services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: warehouse-backend
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_ACCESS_TOKEN_EXPIRATION=15m
      - JWT_REFRESH_TOKEN_EXPIRATION=7d
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: unless-stopped
    networks:
      - warehouse-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # ğŸ‘‡ ë¹Œë“œ ì‹œì ì— ì´ ê°’ì„ ì „ë‹¬í•©ë‹ˆë‹¤.
        - NEXT_PUBLIC_API_URL=${BACKEND_URL}
    container_name: warehouse-frontend
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      # - NEXT_PUBLIC_API_URL=http://backend:3001/api
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - warehouse-network
networks:
  warehouse-network:
    driver: bridge
